# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Prevent Python from buffering stdout/stderr
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy project files
COPY pyproject.toml README.md ./
COPY src ./src

# Install dependencies and package
RUN pip install --no-cache-dir .

# Default command to run the MCP server over stdio
ENTRYPOINT ["devrev-mcp"]
